services:
  mysql:
    image: mysql:latest
    container_name: combinations_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-combinations_db}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-password}"]
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  api:
    build: .
    container_name: combinations_api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-combinations_db}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
